server:
  port: 8004
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://192.168.137.128:3306/nacos_user?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    druid:
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
